pipeline:
  build_dry_run:
    when:
      branch: master
      event: [ pull_request, push ]
    secrets: [ docker_username, docker_password ]
    image: plugins/docker
    repo: dewjam/preso-nginx
    build_args: VERSION="0.0.${DRONE_BUILD_NUMBER}"
    dry_run: true
    tag:
      - snapshot
      - "0.0.${DRONE_BUILD_NUMBER}"

  publish_image_snapshot:
      when:
        branch: master
        event: push
      secrets: [ docker_username, docker_password ]
      image: plugins/docker
      repo: dewjam/preso-nginx
      build_args: VERSION="0.0.${DRONE_BUILD_NUMBER}"
      tag:
        - snapshot
        - "0.0.${DRONE_BUILD_NUMBER}"

  publish_image_release:
    when:
      branch: refs/tags/*
      event: tag
    secrets: [ docker_username, docker_password ]
    image: plugins/docker
    repo: dewjam/preso-nginx
    build_args: VERSION="0.0.${DRONE_BUILD_NUMBER}"
    tag:
      - latest
      - "${DRONE_TAG##v}"

  deployment-to-k8s:
      when:
        branch: master
        event: push
      image: dewjam/kubectl:latest
      secrets: [ kube_config ]
      commands:
        - echo "$USER"
        - echo $KUBE_CONFIG > kube_config
        - kubectl --context kube_config config get-contexts
