apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: preso-nginx
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 3
  template:
    metadata:
      labels:
        name: preso-nginx
    spec:
      containers:
      - name: nginx
        image: dewjam/preso-nginx
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-html
      volumes:
      - name: nginx-html
        configMap:
          name: nginx-html-config
