apiVersion: v1
kind: Service
metadata:
  name: preso-nginx-service
  labels:
    name: preso-nginx-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    name: preso-nginx
